global class CdpOptimizationObjectiveInputRepresentation {
	global String description;
	global String formula;
	global List<ConnectApi.CdpOptimizationConditionFormulaInputRepresentation> formulas;
	global String name;
	global ConnectApi.CdpOptimizationObjectiveEnum type;
	global CdpOptimizationObjectiveInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}