global class CdpOptimizationSourceDataRepresentation {
	global List<ConnectApi.CdpOptimizationConditionFieldRepresentation> dataFilters;
	global String id;
	global ConnectApi.CdpOptimizationInputTypeEnum inputType;
	global String name;
	global CdpOptimizationSourceDataRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}