global class DataCleanRoomProvider {
	global String dataCloudOrgId;
	global String description;
	global String domainUrl;
	global String logoUrl;
	global String offCoreTenantId;
	global List<String> templateNames;
	global DataCleanRoomProvider() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}