global class ResourcesOutputRep {
	global List<ConnectApi.AssetSearchResultRep> assetSearchResults;
	global List<ConnectApi.ErrorMessagesRep> error;
	global List<ConnectApi.ProviderSearchResultRep> providerSearchResults;
	global ResourcesOutputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}