global class BenefitDisbursementDetail {
	global Double adjustmentAmount;
	global String approvalStatus;
	global List<publicsectrsltn.BenefitDisbursementAdjDetail> benefitDisbursementAdjs;
	global String category;
	global Datetime endDate;
	global Double entitlementAmount;
	global String id;
	global String name;
	global String paymentStatus;
	global Double payoutAmount;
	global String recipientId;
	global Datetime startDate;
	global Object clone() { }

}